/**
 * Database Backup Service
 *
 * Runs a weekly cron job every Monday at 09:00 (server time) that:
 *   1. Dumps the entire MySQL/TiDB database using mysqldump.
 *   2. Emails the resulting .sql file as an attachment to lukusdavey@gmail.com
 *      via the existing SendGrid-based email service.
 *
 * This module is imported once in server/_core/index.ts so the cron job is
 * registered as part of the running Express process and fires reliably as long
 * as the app is deployed.
 */

import { execSync } from 'child_process';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import cron from 'node-cron';
import { ENV } from './_core/env';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const RECIPIENT_EMAIL = 'lukusdavey@gmail.com';
const BACKUP_DIR = path.join(__dirname, '../backups');

/**
 * Parse a mysql:// connection string into its component parts.
 * Expected format: mysql://user:password@host:port/database
 */
function parseDbUrl(url: string) {
  const match = url.match(/mysql:\/\/([^:]+):([^@]+)@([^:]+):(\d+)\/(.+)/);
  if (!match) {
    throw new Error(
      `[BackupService] Invalid DATABASE_URL format. Expected mysql://user:password@host:port/database`
    );
  }
  const [, user, password, host, port, database] = match;
  return { user, password, host, port, database };
}

/**
 * Perform the database dump and email it to the recipient.
 */
async function runBackup(): Promise<void> {
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
  const backupFile = path.join(BACKUP_DIR, `backup-${timestamp}.sql`);

  console.log(`[BackupService] Starting backup at ${new Date().toISOString()}`);

  // ── 1. Validate credentials ─────────────────────────────────────────────────
  const databaseUrl = ENV.databaseUrl;
  const apiKey = ENV.emailPassword;
  const emailFrom = ENV.emailFrom || 'Nu Performance Nutrition <noreply@nunutrition.com>';

  if (!databaseUrl) {
    console.error('[BackupService] DATABASE_URL is not set — aborting backup.');
    return;
  }
  if (!apiKey) {
    console.error('[BackupService] EMAIL_PASSWORD (SendGrid API key) is not set — aborting backup.');
    return;
  }

  // ── 2. Create backup directory ───────────────────────────────────────────────
  if (!fs.existsSync(BACKUP_DIR)) {
    fs.mkdirSync(BACKUP_DIR, { recursive: true });
  }

  // ── 3. Run mysqldump ─────────────────────────────────────────────────────────
  let { user, password, host, port, database } = parseDbUrl(databaseUrl);

  console.log(`[BackupService] Dumping database "${database}" from ${host}:${port}…`);

  // Use MYSQL_PWD env var to avoid the password appearing in the process list.
  const dumpCommand = [
    'mysqldump',
    `--host=${host}`,
    `--port=${port}`,
    `--user=${user}`,
    '--ssl-mode=REQUIRED',
    '--single-transaction',
    '--routines',
    '--triggers',
    `--databases ${database}`,
    `> "${backupFile}"`,
  ].join(' ');

  try {
    execSync(dumpCommand, {
      env: { ...process.env, MYSQL_PWD: password },
      stdio: ['ignore', 'pipe', 'pipe'],
    });
  } catch (err) {
    console.error('[BackupService] mysqldump failed:', err);
    throw err;
  }

  const fileSizeKb = Math.round(fs.statSync(backupFile).size / 1024);
  console.log(`[BackupService] Dump complete: ${backupFile} (${fileSizeKb} KB)`);

  // ── 4. Send email via SendGrid ───────────────────────────────────────────────
  console.log(`[BackupService] Sending backup email to ${RECIPIENT_EMAIL}…`);

  const dateLabel = new Date().toLocaleDateString('en-GB', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const parseEmailAddress = (str: string): { email: string; name?: string } => {
    const m = str.match(/^(.+?)\s*<(.+?)>$/);
    return m ? { name: m[1].trim(), email: m[2].trim() } : { email: str.trim() };
  };

  const payload = {
    personalizations: [{ to: [{ email: RECIPIENT_EMAIL }] }],
    from: parseEmailAddress(emailFrom),
    subject: `Weekly Database Backup — Nu Performance Nutrition (${dateLabel})`,
    content: [
      {
        type: 'text/plain',
        value: `Please find attached the weekly database backup for Nu Performance Nutrition.\n\nBackup date: ${dateLabel}\nFile size: ${fileSizeKb} KB\n\nThis is an automated message.`,
      },
      {
        type: 'text/html',
        value: `
<p>Please find attached the weekly database backup for <strong>Nu Performance Nutrition</strong>.</p>
<ul>
  <li><strong>Backup date:</strong> ${dateLabel}</li>
  <li><strong>File size:</strong> ${fileSizeKb} KB</li>
</ul>
<p style="color:#999;font-size:12px;">This is an automated message generated by the Nu Performance Nutrition server.</p>
        `.trim(),
      },
    ],
    attachments: [
      {
        content: fs.readFileSync(backupFile).toString('base64'),
        filename: path.basename(backupFile),
        type: 'application/sql',
        disposition: 'attachment',
      },
    ],
  };

  const response = await fetch('https://api.sendgrid.com/v3/mail/send', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${apiKey}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(payload),
  });

  if (response.ok || response.status === 202) {
    console.log(`[BackupService] Email sent successfully to ${RECIPIENT_EMAIL}.`);
  } else {
    const errorText = await response.text();
    throw new Error(`[BackupService] SendGrid error ${response.status}: ${errorText}`);
  }

  // ── 5. Clean up local file ───────────────────────────────────────────────────
  fs.unlinkSync(backupFile);
  console.log(`[BackupService] Local backup file removed.`);
}

/**
 * Register the weekly cron job.
 * Schedule: every Monday at 09:00 server time  →  cron expression "0 9 * * 1"
 *
 * Call this function once during server startup.
 */
export function startBackupSchedule(): void {
  // Run every Monday at 09:00
  cron.schedule('0 9 * * 1', () => {
    runBackup().catch((err) => {
      console.error('[BackupService] Unhandled error during backup:', err);
    });
  });

  console.log('[BackupService] Weekly backup scheduled — every Monday at 09:00.');
}
